---
title: "Scatter_Plot_Matrix"
output: html_document
date: "2025-04-03"
---

```{r setup, include=FALSE}

#Run only in chunk:
knitr::opts_knit$set(root.dir = '/Users/robertvandervelde/Library/CloudStorage/GoogleDrive-robertvandervelde@sydshafferlab.com/My Drive/Vander_Velde_Share/Experiments/RV143')

getwd()

```


#Load Libraries:
```{r, include=FALSE}

getwd()

rm(list = ls())
library(ggplot2)
library(GGally)
library(ggdist)
library(ggrastr)

#Cairo requires XQuartz to be installed on the system:
library(Cairo)

library(scales)
library(grid)
library(viridis) 

library(extrafont)

```

#Set fonts and sizes:
```{r, include=FALSE}

font_type <- "Helvetica Neue"
font_color <- "black"
font_size <- 25

```

#Load data:
```{r, include=FALSE}

df_remove_spike_ins <- read.csv('2024_10_23_gDNA_Sequencing/Step3_40bp_Scaffold_90Match_3mm/Post_Cluster_Analysis/Organized_Data/counts_without_spike_ins.csv', row.names = 1)

#Change column names:
colnames(df_remove_spike_ins) <- c("Pre1","1A","1B","Pre2","2A","2B")

```

#Get reads per million:
```{r, include=FALSE}

df_remove_spike_ins_reads_per_million <- df_remove_spike_ins*1000000/colSums(df_remove_spike_ins)

```


#Define functions:
```{r, include=FALSE}

scale <- 120000

raster_scatter <- function(data, mapping, ...) {
  x_name <- as.character(mapping$x)[2]
  y_name <- as.character(mapping$y)[2]
  p <- ggplot(data = data, mapping = mapping) +
    geom_point_rast(raster.dpi = 300) +  # Rasterized points
    scale_x_continuous(limits = c(0, scale), expand = c(0, 0)) +  
    scale_y_continuous(limits = c(0, scale), expand = c(0, 0)) +  
    theme_bw() +
    theme(
    text = element_text(family = font_type, size = font_size, color = font_color),
    axis.text.y = element_text(family = font_type, size = font_size, color = font_color),
    axis.text.x = element_text(family = font_type, size = font_size, color = font_color, angle = 90, hjust = 1, vjust = 0.5),
    axis.title = element_text(family = font_type, size = font_size, color = font_color),
    strip.text = element_text(family = font_type, size = font_size, color = font_color),
    plot.title = element_text(family = font_type, size = font_size, color = font_color),
    legend.text = element_text(family = font_type, size = font_size, color = font_color),
    legend.title = element_text(family = font_type, size = font_size, color = font_color)
  )
  
  # Add red border for specific cells, requires ` to handle numbers at the beginning:
  if ((x_name == "`1A`" && y_name == "`1B`") || (x_name == "`2A`" && y_name == "`2B`")) {
    p <- p + theme(panel.border = element_rect(colour = "red", fill = NA))
  }
  
  return(p)
  
}

custom_cor <- function(data, mapping, ...) {
  #Determine if correlation should be highlighted:
  x_name <- as.character(mapping$x)[2]
  y_name <- as.character(mapping$y)[2]
  text_color <- if((x_name == "`1B`" && y_name == "`1A`") || 
                       (x_name == "`2B`" && y_name == "`2A`")) "red" else font_color
  
  # Get the correlation values
  x <- eval_data_col(data, mapping$x)
  y <- eval_data_col(data, mapping$y)
  
  # Calculate Pearson correlation and p-value
  pearson_test <- cor.test(x, y, method = "pearson", use = "pairwise.complete.obs")
  pearson_r <- pearson_test$estimate
  pearson_p <- pearson_test$p.value
  
  # Add stars for significance
  pearson_star <- ifelse(pearson_p < 0.05, "*", "")
  
  # Create labels
  correlation_label <- sprintf("r = %.2f%s", 
                           pearson_r, pearson_star)
  
  # Plot
  ggplot(data = data, mapping = mapping) + 
    theme_bw() +
    annotate("text",
             x = 0.5, y = 0.6,
             label = correlation_label, 
             size = font_size/2.8451722208,
             family = font_type,
             color = text_color) +
    theme_void() +
    theme(
      plot.background = element_blank(),
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank(),
      panel.border = element_blank(),
      axis.title = element_blank(),
      axis.text = element_blank(),
      axis.ticks = element_blank()
    )
}

```

#Plot
```{r}

ggpairs(df_remove_spike_ins_reads_per_million,
        upper = list(continuous = custom_cor),
        diag = NULL,
        lower = list(continuous = raster_scatter),
        columnLabels = colnames(df_remove_spike_ins)) +
  theme(
    strip.text = element_text(family = font_type, size = font_size, color = font_color),
    strip.background = element_rect(fill = "white", color = NA),
    panel.spacing = unit(1.5, "lines")
  )

ggsave(
  "2024_10_23_gDNA_Sequencing/Step3_40bp_Scaffold_90Match_3mm/Post_Cluster_Analysis/Plots/Scatter_Plot_Matrix/Pearson.pdf",
  device = cairo_pdf,
  width = 20,
  height = 18,
  units = "in",
  dpi = 300
)

```






