---
title: "mScarlet3_Distribution"
output: html_document
date: "2025-11-12"
---


```{r setup, include=FALSE}

#Run only in chunk:
knitr::opts_knit$set(root.dir = '/Users/robertvandervelde/Library/CloudStorage/GoogleDrive-robertvandervelde@sydshafferlab.com/My Drive/Vander_Velde_Share/Experiments/RV124')

getwd()

```

#Load Libraries:
```{r, include=FALSE}

rm(list = ls())

library(ggplot2)
library(egg)

```


#Set variable:
```{r, include=FALSE}

font_size <- 8
font_type <- "Helvetica Neue"

panel_dimensions <- c(0.9356,0.9356)
       
```

#Load data:
```{r, include=FALSE}

#List csv files
csv_files <- list.files(path = "Attempt_3/Flow/27JUN2024_Jazz/FlowJo_2025_11_12/Scale_Values", pattern = "\\.csv$", full.names = TRUE)

# Load each CSV file
for (file in csv_files) {
  # Extract the filename without path
  filename <- basename(file)
  
  # Get first 6 characters for the object name
  object_name <- substr(filename, 1, 6)
  
  # Read the CSV and assign to the object name
  assign(object_name, read.csv(file))

}

```



#Plot a distribution plot Well 1:
```{r}

p <- ggplot(Well_1, aes(x = mCherry)) +
  geom_density(aes(y = after_stat(count)),
               adjust = 0.5,
               color = "red",
               fill = "red",
               alpha = 0.3) +
  geom_vline(xintercept = 175) +
  labs(x = "",
       y = "",
       title = paste0(sprintf("%.2f", length(Well_1$mCherry[Well_1$mCherry > 175]) * 100 / length(Well_1$mCherry)), "%")) +
  theme_bw() +
  scale_x_log10(limits = c(1, 20000),
                expand = expansion(mult = c(0, 0))) +
  scale_y_continuous(expand = expansion(mult = c(0,0.1))) +
  theme(
    text = element_text(family = font_type, size = font_size, color = "black"),
    panel.background = element_rect(fill = "white"),
    plot.background = element_rect(fill = "white"),
    axis.text.x = element_text(family = font_type, size = font_size, color = "black"),
    axis.text.y = element_text(family = font_type, size = font_size, color = "black"),
    axis.title = element_text(family = font_type, size = font_size, color = "black"),
    plot.title = element_text(family = font_type, size = font_size, color = "black"),
    legend.text = element_text(family = font_type, size = font_size, color = "black")
  )

p

#Change panel size:
p <- set_panel_size(p, 
                    width  = unit(panel_dimensions[1], "inches"),
                    height = unit(panel_dimensions[2], "inches"))


ggsave(p, filename = "Attempt_3/Plots/Well_1.pdf",
       device = cairo_pdf,
       width = 3, 
       height = 3)




```



#Plot a distribution plot Well 2:
```{r}

p <- ggplot(Well_2, aes(x = mCherry)) +
  geom_density(aes(y = after_stat(count)),
               adjust = 0.5,
               color = "red",
               fill = "red",
               alpha = 0.3) +
  geom_vline(xintercept = 175) +
  labs(x = "",
       y = "",
       title = paste0(sprintf("%.2f", length(Well_2$mCherry[Well_2$mCherry > 175]) * 100 / length(Well_2$mCherry)), "%")) +
  theme_bw() +
  scale_x_log10(limits = c(1, 20000),
                expand = expansion(mult = c(0, 0))) +
  scale_y_continuous(expand = expansion(mult = c(0,0.1))) +
  theme(
    text = element_text(family = font_type, size = font_size, color = "black"),
    panel.background = element_rect(fill = "white"),
    plot.background = element_rect(fill = "white"),
    axis.text.x = element_text(family = font_type, size = font_size, color = "black"),
    axis.text.y = element_text(family = font_type, size = font_size, color = "black"),
    axis.title = element_text(family = font_type, size = font_size, color = "black"),
    plot.title = element_text(family = font_type, size = font_size, color = "black"),
    legend.text = element_text(family = font_type, size = font_size, color = "black")
  )

p

#Change panel size:
p <- set_panel_size(p, 
                    width  = unit(panel_dimensions[1], "inches"),
                    height = unit(panel_dimensions[2], "inches"))


ggsave(p, filename = "Attempt_3/Plots/Well_2.pdf",
       device = cairo_pdf,
       width = 3, 
       height = 3)




```


#Plot a distribution plot Well 2:
```{r}

p <- ggplot(Well_3, aes(x = mCherry)) +
  geom_density(aes(y = after_stat(count)),
               adjust = 0.5,
               color = "red",
               fill = "red",
               alpha = 0.3) +
  geom_vline(xintercept = 175) +
  labs(x = "",
       y = "",
       title = paste0(sprintf("%.2f", length(Well_3$mCherry[Well_3$mCherry > 175]) * 100 / length(Well_3$mCherry)), "%")) +
  theme_bw() +
  scale_x_log10(limits = c(1, 20000),
                expand = expansion(mult = c(0, 0))) +
  scale_y_continuous(expand = expansion(mult = c(0,0.1))) +
  theme(
    text = element_text(family = font_type, size = font_size, color = "black"),
    panel.background = element_rect(fill = "white"),
    plot.background = element_rect(fill = "white"),
    axis.text.x = element_text(family = font_type, size = font_size, color = "black"),
    axis.text.y = element_text(family = font_type, size = font_size, color = "black"),
    axis.title = element_text(family = font_type, size = font_size, color = "black"),
    plot.title = element_text(family = font_type, size = font_size, color = "black"),
    legend.text = element_text(family = font_type, size = font_size, color = "black")
  )

p

#Change panel size:
p <- set_panel_size(p, 
                    width  = unit(panel_dimensions[1], "inches"),
                    height = unit(panel_dimensions[2], "inches"))


ggsave(p, filename = "Attempt_3/Plots/Well_3.pdf",
       device = cairo_pdf,
       width = 3, 
       height = 3)




```




#Plot a distribution plot Well 4:
```{r}

p <- ggplot(Well_4, aes(x = mCherry)) +
  geom_density(aes(y = after_stat(count)),
               adjust = 0.5,
               color = "red",
               fill = "red",
               alpha = 0.3) +
  geom_vline(xintercept = 175) +
  labs(x = "",
       y = "",
       title = paste0(sprintf("%.2f", length(Well_4$mCherry[Well_4$mCherry > 175]) * 100 / length(Well_4$mCherry)), "%")) +
  theme_bw() +
  scale_x_log10(limits = c(1, 20000),
                expand = expansion(mult = c(0, 0))) +
  scale_y_continuous(expand = expansion(mult = c(0,0.1))) +
  theme(
    text = element_text(family = font_type, size = font_size, color = "black"),
    panel.background = element_rect(fill = "white"),
    plot.background = element_rect(fill = "white"),
    axis.text.x = element_text(family = font_type, size = font_size, color = "black"),
    axis.text.y = element_text(family = font_type, size = font_size, color = "black"),
    axis.title = element_text(family = font_type, size = font_size, color = "black"),
    plot.title = element_text(family = font_type, size = font_size, color = "black"),
    legend.text = element_text(family = font_type, size = font_size, color = "black")
  )

p

#Change panel size:
p <- set_panel_size(p, 
                    width  = unit(panel_dimensions[1], "inches"),
                    height = unit(panel_dimensions[2], "inches"))


ggsave(p, filename = "Attempt_3/Plots/Well_4.pdf",
       device = cairo_pdf,
       width = 3, 
       height = 3)




```





