---
title: "Check_Recovery_Library"
output: html_document
date: "2025-02-18"
---

```{r setup, include=FALSE}

#Run only in chunk:
knitr::opts_knit$set(root.dir = '/Users/robertvandervelde/Library/CloudStorage/GoogleDrive-robertvandervelde@sydshafferlab.com/My Drive/Vander_Velde_Share/Experiments/RV143')

getwd()

```


#Remove variables:
```{r, include=FALSE}

rm(list = ls())

library(ggplot2)

```

#Load barcodes data:
```{r, include=FALSE}

#Load barcodes from sequencing: 
sequenced_barcodes <- c(read.table("2025_2_13_Recovery_Library_Sequencing/Data/sequences_37_56.txt", header = FALSE, sep = " "))

gibson_assembly_sequences <- read.csv("2024_10_23_gDNA_Sequencing/Step3_40bp_Scaffold_90Match_3mm/Post_Cluster_Analysis/Organized_Data/Gibson_Assembly_Sequences_20241212.csv", header = FALSE)

gibson_assembly_barcodes <- substring(gibson_assembly_sequences$V1, 50, 69)



```


#Check the number of matches:
```{r}

match_df <- data.frame(value = gibson_assembly_barcodes)

match_df$matches <- sapply(gibson_assembly_barcodes, function(x)
sum(sequenced_barcodes$V1 == x))

colnames(match_df) <- c("Lineage_Barcode","Number_of_Matches")

match_df

```

#Compare length of sequenced barcodes to number of matches:
```{r}

length(sequenced_barcodes$V1)

sum(match_df$matches)

sum(match_df$matches)/length(sequenced_barcodes$V1)


```

#Set font size and type:
```{r, include=FALSE}

font_type <- "Helvetica Neue"
font_size <- 8

```

#Plot barcode representation:
```{r}


ggplot(match_df, aes(x=Lineage_Barcode, y=Number_of_Matches)) + 
  geom_bar(stat = "identity") +
  theme_classic() +
  theme(axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        text = element_text(family = font_type, size = font_size, color = "black"),
        axis.text = element_text(family = font_type, size = font_size, color = "black")
        ) +
  scale_y_continuous(expand = c(0,0), limits = c(0, 300000)) +
  labs(
    x="Lineage Barcode",
    y="# of Matching Reads"
  )


ggsave("2025_2_13_Recovery_Library_Sequencing/Plots/Barplot.pdf", plot = last_plot(), device = cairo_pdf, width = 1.8, height = 1.5)

#Plot with x-axis to view order of barcodes:
ggplot(match_df, aes(x=Lineage_Barcode, y=Number_of_Matches)) + 
  geom_bar(stat = "identity") +
  theme_classic() +
  theme(axis.text.x=element_text(angle = 90),
        axis.ticks.x=element_blank(),
        text = element_text(family = font_type, size = font_size, color = "black"),
        axis.text = element_text(family = font_type, size = font_size, color = "black")
        ) +
  scale_y_continuous(expand = c(0,0)) +
  labs(
    x="Lineage Barcode",
    y="# of Matching Reads"
  )
  

```







