---
title: "Add_cNMF_Data"
output: html_document
date: "2025-08-21"
---

```{r setup, include=FALSE}

#Run only in chunk:
knitr::opts_knit$set(root.dir = '/Users/robertvandervelde/Library/CloudStorage/GoogleDrive-robertvandervelde@sydshafferlab.com/My Drive/Vander_Velde_Share/Experiments/RV143')

getwd()

```

#Remove variables and load libraries:
```{r, include=FALSE}

rm(list = ls())
library(Seurat)
library(ggplot2)
library(reshape2)

library(glmnet)

```

#Set variable:
```{r, include=FALSE}

font_size <- 8
font_type <- "Helvetica Neue"

```

#Load Seurat object:
```{r, include=FALSE}

seurat_strict_barcode_requirements <- readRDS("RV143_Comb_20250407_20250508_Seq/Post_Cluster_Analysis/Organized_Data/Create_Seurat_Objects/seurat_strict_barcode_requirements")

```

#Load cNMF scores:
```{r, include=FALSE}

#Need to determine if right:
cNMF_usages <- read.table("RV143_Comb_20250407_20250508_Seq/Post_Cluster_Analysis/Organized_Data/cNMF/RV143_cNMF_output/RV143_cNMF_Part1/RV143_cNMF_Part1.usages.k_14.dt_0_01.consensus.txt", sep = "\t", row.names = 1, header = TRUE)

```


#Add usages to the Seurat object:
```{r, include=FALSE}

# Create a assay from the cNMF usages

seurat_strict_barcode_requirements[["cNMF"]] <- CreateAssayObject(counts = t(as.matrix(cNMF_usages[intersect(rownames(cNMF_usages), colnames(seurat_strict_barcode_requirements)), ])))

```

#Test integration of cNMF data:
```{r, include=FALSE}

cNMF_usages_shuffled <- cNMF_usages[sample(nrow(cNMF_usages)),]

seurat_strict_barcode_requirements[["cNMF_shuffled"]] <- CreateAssayObject(counts = t(as.matrix(cNMF_usages_shuffled[intersect(rownames(cNMF_usages_shuffled), colnames(seurat_strict_barcode_requirements)), ])))

#View subset of data to confirm correct integration:
GetAssayData(object = seurat_strict_barcode_requirements, assay = "cNMF")[1:5,1:5]

GetAssayData(object = seurat_strict_barcode_requirements, assay = "cNMF_shuffled")[1:5,1:5]

#Remove chuffled cNMF:
seurat_strict_barcode_requirements[["cNMF_shuffled"]] <- NULL

```

#Create dataframe with untransduce, transduced and targeted loadings. Don't show targeted in untransduced (though this is in the cNMF):
```{r, include=FALSE}

cNMF_df <- as.data.frame(t(GetAssayData(seurat_strict_barcode_requirements, assay = "cNMF")))
cNMF_df$Sample <- seurat_strict_barcode_requirements$orig.ident

cNMF_df$Mini_Library_Assignment <- seurat_strict_barcode_requirements$Mini_Library_Assignment

#Remove targeted cells in untransduced:
cNMF_df <- cNMF_df[!(cNMF_df$Sample == "Untransduced" & !is.na(cNMF_df$Mini_Library_Assignment)), ]

#Create combined dataframe with "Type" replacing enriched 
cNMF_df_combine_type <- cNMF_df
cNMF_df_combine_type$Type <- cNMF_df$Sample

cNMF_df_combine_type$Type[!is.na(cNMF_df_combine_type$Mini_Library_Assignment) & cNMF_df_combine_type$Sample == "Enriched"] <- "Targeted"

#Remove redundant columns:
cNMF_df_combine_type$Sample <- NULL
cNMF_df_combine_type$Mini_Library_Assignment <- NULL

#Add cell barcodes as column:
cNMF_df_combine_type$Cell_Barcode <- rownames(cNMF_df_combine_type)

#Creat melted dataframe:
cNMF_df_combine_type_melted <- melt(cNMF_df_combine_type, id.vars = c("Cell_Barcode","Type"))
colnames(cNMF_df_combine_type_melted) <- c("Cell_Barcode", "Type", "Loading", "Score")


```

```{r}

ggplot(cNMF_df_combine_type_melted, aes(x = Loading, y = Score, fill = Type)) +
 geom_boxplot(position = position_dodge(width = 0.9)) +
  theme_bw() +
  theme(
    text = element_text(family = font_type, size = font_size, color = "black"),
    panel.background = element_rect(fill = "white"),
    plot.background = element_rect(fill = "white"),
    axis.text = element_text(family = font_type, size = font_size, color = "black"),
    axis.title = element_text(family = font_type, size = font_size, color = "black"),
    legend.title = element_text(family = font_type, size = font_size, color = "black"),
    legend.text = element_text(family = font_type, size = font_size, color = "black"),
    axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1),
    aspect.ratio = 1
  )

```

```{r, include=FALSE}

#Replace Type with numbers:
cNMF_df_combine_type_melted_numeric <- cNMF_df_combine_type_melted

cNMF_df_combine_type_melted_numeric[cNMF_df_combine_type_melted$Type == "Untransduced",]$Type <- 1
cNMF_df_combine_type_melted_numeric[cNMF_df_combine_type_melted$Type == "Enriched",]$Type <- 2
cNMF_df_combine_type_melted_numeric[cNMF_df_combine_type_melted$Type == "Targeted",]$Type <- 3
cNMF_df_combine_type_melted_numeric$Type <- as.numeric(cNMF_df_combine_type_melted_numeric$Type)

cNMF_df_combine_type_melted_numeric$Loading <- as.numeric(substring(cNMF_df_combine_type_melted$Loading, 2))

test <- cv.glmnet(cbind(cNMF_df_combine_type_melted_numeric$Type,cNMF_df_combine_type_melted_numeric$Loading), cNMF_df_combine_type_melted_numeric$Score, alpha = 1)

test2 <- cv.glmnet(cbind(cNMF_df_combine_type_melted_numeric$Score,cNMF_df_combine_type_melted_numeric$Loading), cNMF_df_combine_type_melted_numeric$Type, alpha = 1)

test2$lambda.min

test <- cv.glmnet(cbind(cNMF_df_combine_type_melted[cNMF_df_combine_type_melted$Type != "Untransduced",]$Type,cNMF_df_combine_type_melted[cNMF_df_combine_type_melted$Type != "Untransduced",]$Loading), cNMF_df_combine_type_melted[cNMF_df_combine_type_melted$Type != "Untransduced",]$Score, alpha = 1)

coef(test, s = "lambda.min")

mod <- aov(Score ~ Type * Loading,
  data = cNMF_df_combine_type_melted
)

plot(mod, which = 2)

summary(mod)



```

